/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#000666",
        "primary-container": "#1a237e",
        "on-primary": "#ffffff",
        "on-primary-container": "#8690ee",
        surface: "#f8fafb",
        "surface-dim": "#d8dadb",
        "surface-bright": "#f8fafb",
        "surface-container": "#eceeef",
        "surface-container-low": "#f2f4f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#454652",
        "secondary-container": "#96a5ff",
        "secondary-fixed": "#dee0ff",
        "secondary-fixed-dim": "#bac3ff",
        "on-secondary-container": "#27378a",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#eff1f2",
        "inverse-primary": "#bdc2ff",
        outline: "#767683",
        "outline-variant": "#c6c5d4",
        error: "#ba1a1a",
        "on-error-container": "#93000a",
        "surface-tint": "#4c56af",
      },
      fontFamily: {
        headline: ["Manrope", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
